import React, { useState, useEffect, useCallback } from 'react';
import { Player } from '../types';
import { generateFreeAgents } from '../services/geminiService';
import { PlayerCard } from './PlayerCard';
import { RefreshCw, Loader2 } from 'lucide-react';

interface MarketViewProps {
  budget: number;
  onHire: (player: Player) => void;
  currentRosterCount: number;
}

export const MarketView: React.FC<MarketViewProps> = ({ budget, onHire, currentRosterCount }) => {
  const [agents, setAgents] = useState<Player[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchAgents = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      // Simulate network delay if needed, but Gemini is usually fast enough.
      const newAgents = await generateFreeAgents(4, budget); // Generate 4 agents at a time
      setAgents(newAgents);
    } catch (err) {
      setError("Failed to scout new players. Check API connection.");
    } finally {
      setIsLoading(false);
    }
  }, [budget]);

  // Initial fetch
  useEffect(() => {
    if (agents.length === 0) {
      fetchAgents();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleHire = (player: Player) => {
    onHire(player);
    setAgents(prev => prev.filter(p => p.id !== player.id));
  };

  return (
    <div className="p-6 w-full max-w-7xl mx-auto">
      <div className="flex justify-between items-center mb-8">
        <div>
            <h2 className="text-3xl font-bold text-white">Transfer Market</h2>
            <p className="text-gray-400">Scout free agents generated by AI. Prices fluctuate based on stats.</p>
        </div>
        <button 
            onClick={fetchAgents}
            disabled={isLoading}
            className="flex items-center gap-2 bg-gray-800 hover:bg-gray-700 text-white px-4 py-2 rounded transition-colors disabled:opacity-50"
        >
            {isLoading ? <Loader2 className="animate-spin" size={18} /> : <RefreshCw size={18} />}
            Scout New Talent
        </button>
      </div>

      {error && (
          <div className="p-4 bg-red-900/30 border border-red-800 text-red-200 rounded mb-6">
              {error}
          </div>
      )}

      {isLoading && agents.length === 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {[1,2,3,4].map(i => (
                <div key={i} className="h-64 bg-gray-800 rounded-lg animate-pulse"></div>
            ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {agents.map(player => (
                <PlayerCard 
                    key={player.id} 
                    player={player} 
                    actionLabel={currentRosterCount >= 5 ? "Roster Full" : `Sign for $${player.marketValue.toLocaleString()}`}
                    onAction={handleHire}
                    actionDisabled={budget < player.marketValue || currentRosterCount >= 5}
                    className="h-full"
                />
            ))}
        </div>
      )}
      
      {!isLoading && agents.length === 0 && !error && (
          <div className="text-center text-gray-500 py-20">
              No agents found. Try scouting again.
          </div>
      )}
    </div>
  );
};